# NumPy Basics

NumPy is a more like arrays as in C but powered with fast and advanced algorithms in the background.

It includes:
- Basic functions for matrices (transpose, multiplication, ranking, ect.)
- Various random number generators
- Doing linear algerba related calculations

To start with NumPy we need:

In [1]:
import numpy as np

Some example functions

In [4]:
print(np.cos(np.pi))
print(np.sqrt(2))
print(np.sqrt(2)**2)

-1.0
1.4142135623730951
2.0000000000000004


## Defining arrays
### From lists

In [6]:
vec1 = np.array([1, 3, 5])
print (vec1)
print()
mat1 = np.array([[1,3,5], [7, 9, 11], [13, 15, 17]])
print (mat1)

[1 3 5]

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


### Transpose a matrix

In [7]:
print(mat1.T)

[[ 1  7 13]
 [ 3  9 15]
 [ 5 11 17]]


## Other ways to define arrays
### Range and Linear spaced range

In [11]:
vec2 = np.arange(1, 10)
vec3 = np.arange(0, 10, 2)
vec4 = np.linspace(0, 100, 12)
print (vec2, vec3, vec4, sep='\n')


[1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[  0.           9.09090909  18.18181818  27.27272727  36.36363636
  45.45454545  54.54545455  63.63636364  72.72727273  81.81818182
  90.90909091 100.        ]


In [12]:
print(len(vec4))

12


## Conversion from vector to matrix

In [13]:
mat2 = vec4.reshape(3,4) # See: rows x columns is the order of the parameters
print(mat2)

[[  0.           9.09090909  18.18181818  27.27272727]
 [ 36.36363636  45.45454545  54.54545455  63.63636364]
 [ 72.72727273  81.81818182  90.90909091 100.        ]]


## Generation of random numbers

In [16]:
from numpy import random
rvec1 = random.randint(20)
print(rvec1)

16


In [17]:
from pydoc import doc

In [18]:
print(doc(random.randint))

Python Library Documentation: built-in function randint

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; see `random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distr

In [21]:
rvec2 = random.randint(1.0, 100, size=(2,3), dtype=np.uint8)
print(rvec2)

[[23 22 32]
 [51  5  6]]


## Trivial matrices
- Zeroes
- Ones
- Identity matrix

In [28]:
z = np.zeros([2,3])
o = np.ones([2,3])
e = np.eye(3)
print(z, o, e, sep='\n\n')

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
