# Numpy Examples
## The basics

In [2]:
import numpy as np
print(np.cos(np.pi))
print(np.sqrt(2.0))
print(np.log(np.exp(5.2)))

-1.0
1.4142135623730951
5.2


## Converting python data types to Numpy arrays

In [3]:
python_list = [1, 2, 3]
python_matrix = [[1, 2, 3], [4,5,6], [7,8,9]]
np_vec = np.array(python_list)
np_mat = np.array(python_matrix)

print(np_vec)
print(np_mat)

[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Other ways to create Numpy arrays

In [3]:
python_list = [1, 2, 3]
python_matrix = [[1, 2, 3], [4,5,6], [7,8,9]]
np_vec = np.array(python_list)
np_mat = np.array(python_matrix)

print(np_vec)
print(np_mat)

[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
vec2 = np.arange(0, 15)
print(vec2)
print('')
print(np.arange(3,21,6))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [7]:
vec4 = np.linspace(0, 5, 10)
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [9]:
mat_from_vect = vec4.reshape(2,5)
print(mat_from_vect)

[[0.         0.55555556 1.11111111 1.66666667 2.22222222]
 [2.77777778 3.33333333 3.88888889 4.44444444 5.        ]]


### built-in matrices

In [11]:
print(np.zeros(5))
print(np.ones(5))
print('')
print(np.eye(5))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Element-wise operations

In [12]:
vec1 = np.arange(1, 10)
vec2 = np.arange(11,20)
print(vec1, vec2, sep="\n\n")

[1 2 3 4 5 6 7 8 9]

[11 12 13 14 15 16 17 18 19]


In [13]:
print(vec1+vec2)
print(vec1*vec2)
print(vec1/2)

[12 14 16 18 20 22 24 26 28]
[ 11  24  39  56  75  96 119 144 171]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


## Matrix multiplication and linear equation solve

In [15]:
mat = [[1,2,3], [4,5,6], [7,8,9]]
vec = [10, 11, 12]
product = np.matmul(mat,vec)
print(product)

[ 68 167 266]


In [17]:
print(np.linalg.solve(mat, product))
print(np.linalg.inv(mat))

[-4.8 40.6 -2.8]
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


## Unique value search

In [18]:
vec = ["orange", "banana", 6.0, "orange", "apple", "banana", "apple", "peach"]
nparr = np.array(vec)
print(np.unique(nparr))

['6.0' 'apple' 'banana' 'orange' 'peach']


## Random value generation

In [19]:
standardrandom = np.random.randn(10, 5)
uniformrandom = np.random.rand(10, 5)
print(standardrandom, uniformrandom, sep="\n\n")

[[ 2.04400715 -0.5179509  -1.49421018  0.34322297  1.28753352]
 [-0.73162577 -0.3923233  -0.7008889  -1.20794719 -1.12928799]
 [-0.99378902  0.32105166  0.00479031 -0.35131851 -0.63022259]
 [ 0.24565507  1.87898282  0.75499071  0.34477681  0.01005441]
 [-0.31632417 -0.0544549   0.31289684  0.59741104  0.51054735]
 [ 0.85777912  1.09644337 -1.22011242 -0.74395445  1.43861444]
 [-0.59607692 -1.30853747  1.17418777 -0.8898002  -0.3989965 ]
 [-2.05829512 -1.3665412  -0.01698109 -2.23976869 -0.29729309]
 [ 0.7709591  -0.43789044  0.82120376 -1.01686628  2.73689607]
 [-0.33229774  2.33361884 -1.40409033  1.25427853  0.73756155]]

[[0.95363843 0.39864416 0.20512876 0.53312216 0.4853609 ]
 [0.0764637  0.60241278 0.98710587 0.23427971 0.54354885]
 [0.72739356 0.45139234 0.59237039 0.62175221 0.77248079]
 [0.62453812 0.81776856 0.79896764 0.06027176 0.7974757 ]
 [0.61892338 0.53809289 0.1495497  0.80593992 0.00233452]
 [0.92492107 0.01877478 0.78894798 0.9256218  0.64322575]
 [0.03843238 0.32022

### Statistics

In [20]:
print(np.mean(uniformrandom), np.std(uniformrandom), np.min(uniformrandom), np.max(uniformrandom), sep="\n\n")

0.5204107716758668

0.27769593416745414

0.002334517955864368

0.9953571442715813


## Accessing elements by conditions

In [21]:
print(uniformrandom>0.5)

[[ True False False  True False]
 [False  True  True False  True]
 [ True False  True  True  True]
 [ True  True  True False  True]
 [ True  True False  True False]
 [ True False  True  True  True]
 [False False  True False  True]
 [False  True False  True False]
 [ True False  True  True  True]
 [ True False False False False]]


In [23]:
bigelements=uniformrandom[uniformrandom>0.5]
print(bigelements, len(bigelements), sep="\n\n")

[0.95363843 0.53312216 0.60241278 0.98710587 0.54354885 0.72739356
 0.59237039 0.62175221 0.77248079 0.62453812 0.81776856 0.79896764
 0.7974757  0.61892338 0.53809289 0.80593992 0.92492107 0.78894798
 0.9256218  0.64322575 0.62281293 0.6478454  0.58715143 0.86812931
 0.73327217 0.50322476 0.99535714 0.78171858 0.51708513]

29


## Save and load data

In [24]:
np.save("unirandom.npy", uniformrandom)
uniformrandom = []
print(uniformrandom)

[]


In [25]:
uniformrandom = np.load("unirandom.npy")
print(uniformrandom)

[[0.95363843 0.39864416 0.20512876 0.53312216 0.4853609 ]
 [0.0764637  0.60241278 0.98710587 0.23427971 0.54354885]
 [0.72739356 0.45139234 0.59237039 0.62175221 0.77248079]
 [0.62453812 0.81776856 0.79896764 0.06027176 0.7974757 ]
 [0.61892338 0.53809289 0.1495497  0.80593992 0.00233452]
 [0.92492107 0.01877478 0.78894798 0.9256218  0.64322575]
 [0.03843238 0.32022122 0.62281293 0.22302972 0.6478454 ]
 [0.3927832  0.58715143 0.31167682 0.86812931 0.36404097]
 [0.73327217 0.29778979 0.50322476 0.99535714 0.78171858]
 [0.51708513 0.44399649 0.37858198 0.16181367 0.13112735]]


In [33]:
origrandom = uniformrandom.copy()
np.savez("unirandom.npz", uniformrandom = uniformrandom)
unirandom = np.load("unirandom.npz")
uniformrandom = []
uniformrandom = unirandom['uniformrandom']
print("Difference of the loaded and the stored array: ", origrandom-uniformrandom, sep="\n\n")



Difference of the loaded and the stored array: 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
