In [1]:
import numpy as np
import pandas as pd


In [2]:
df1 = pd.DataFrame({'marks':[10,20,30], 'test':[1,2,3], 'speed':[40,50,60]})

In [3]:
 df1

marks  test  speed
0     10     1     40
1     20     2     50
2     30     3     60

In [4]:
print(df1.drop('marks', axis=1))

   test  speed
0     1     40
1     2     50
2     3     60


In [5]:
flowers = pd.Series([2, 3, 5, 4], index=['lily', 'rose', 'daisy', 'lotus'])
flowers['daisy']

5

In [6]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38], [73,39,93,39]))

demo_matrix[:, (1,2)]

array([[35, 74],
       [37, 37],
       [39, 93]])

In [8]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))

demo_matrix[2,3]

39

In [9]:
s1 = pd.Series(['a', 'b'])

s2 = pd.Series(['c', 'd'])

pd.concat([s1, s2])

0    a
1    b
0    c
1    d
dtype: object

In [11]:
pd.concat([s1+s2])

0    ac
1    bd
dtype: object

In [12]:
demo_array = np.arange(10,21)

subset_demo_array = demo_array[0:7]

subset_demo_array[:]= 101

subset_demo_array

array([101, 101, 101, 101, 101, 101, 101])

In [13]:
test_array = [10, 11.5, 12, 13.5, 14,15]   

test_array[2:3]

[12]

In [14]:
np.arange(0,22,6)

array([ 0,  6, 12, 18])